//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeweler.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> IDClient { get; set; }
        public string OrderComposition { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int IDOrderPickupPoint { get; set; }
        public int OrderReceiptCode { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
